### ISSUE TITLE
[TakeNotes v1.2.2 x32] Open Last Note does not open correct note file

### ISSUE THREAD

**Issue by dmm4WiX** [francostellari/NppPlugins#11]
Found with NotePad++ v8.1.2. Steps to reproduce: use 'N' button on toolbar to create a new note file, enter text & save file, close NotePad++, open NotePad++ and click the 'L' button on the toolbar to open the last note, old last note is opened.

**Comment by francostellari** [comment]
Thank you for reporting this issue. I have fixed it in the new version 1.2.3.
