### ISSUE TITLE
[Menu Icons] Icon set for German locale attached

### ISSUE THREAD

**Issue by bege10** [francostellari/NppPlugins#15]
In case you want to supply icons for the German locale I attach my icon set here.
Unfortunately it seems like the naming of the menu items is being changed by translators frequently. That makes icons disappear.

Did you ever consider to use the "command ID match" option instead? I shun the work to make all the changes but it might be less work on the long run. Or do these IDs change as often as the translations?

[DE.zip](https://github.com/francostellari/NppPlugins/files/8100690/DE.zip)

**Comment by francostellari** [comment]
Thank you for sharing the file
