### ISSUE TITLE
Making new take notes default function of firstly opened new txt in notepad++

### ISSUE THREAD

**Issue by loa111** [francostellari/NppPlugins#20]
Making new take notes default function of firstly opened new txt in notepad++.

I would like to completely block default notepad++ new file action like new1, new2, new3 etc.
I would like that take notes new file action is the default function of notepad++.
Creating filename with date and time, will not mess with auto save plugin like new1, new2 is messing with me.
I'm willing to edit any config file in notepad++, or I'm willing to try any modified notepad++ version, if requested is not possible with plugin.

Thank you in advanced, anyway take notes is great plugin.

**Comment by francostellari** [comment]
Perhaps replacing removing the Ctrl+N shortcut from the File/New and assigning it to the TakeNote/New menu would accomplish most of what you want.
