### ISSUE TITLE
Wish:  Autosave when tab looses focus

### ISSUE THREAD

**Issue by nebosite** [francostellari/NppPlugins#22]
This would be similar to what VSCode does and it's really nice.    I move around in the app a lot and would like it autosave more often based on my internal tab activity.  

PS:  Thanks for providing this plugin.  Love it!

**Comment by francostellari** [comment]
Can you explain better what is you desired behavior?
I'm not familiar with your VSCode reference.
Currently you can autosave at often as 1sec.

**Comment by nebosite** [comment]
This is the behavior I'm looking for:
1.  Make some edits in tab #1
2. Switch to tab #2 
Result: tab #1 (and only tab #1) is autosaved.   

Similar situation:
1. Make some edits to tab #1 
2. Switch to a different app
Result: tab #1 (and only tab #1) is autosaved

This is what VSCode does and I love it.   The current plugin for NP++ requires me to change the focus to a different app, then it flips through every single tab, so there is a visual distraction when this happens.

**Comment by francostellari** [comment]
Please take a look at the latest version 2v00 which should implement what you want.
Please note that there are major changes impacting previous features.
If you are ok with this behavior I will eventually push it to the N++ repo.
https://github.com/francostellari/NppPlugins/tree/main/AutoSave

**Comment by nebosite** [comment]
YES!   Perfect!  Thank you!
