### ISSUE TITLE
[Request/suggestion] Add option to "Run current file with Run as Admin" for RunMe 

### ISSUE THREAD

**Issue by JergenRoss** [francostellari/NppPlugins#27]
I have batch script but RunMe don't have run as admin option.
I don't want use "runas" command.

I would like run current file with run as admin option? also shortcut key too.

**Comment by francostellari** [comment]
Hi it is a good idea, please check the new 1v50 here and let me know if it does what you want:
https://github.com/francostellari/NppPlugins/tree/main/RunMe

**Comment by francostellari** [comment]
no reponse

**Comment by JergenRoss** [comment]
Sorry I'm back. I got 1.60v from github. thanks. ok closed this
