### ISSUE TITLE
Autosave don't save any file

### ISSUE THREAD

**Issue by angelohenq** [francostellari/NppPlugins#28]
I have 446 files open in notepad++, to avoid naming all them in native "Save All" option, I installed this plugin but apparently it is not working as expected. I can see the application running something, the tabs change focus quickly, as if the plugin is going through them all to save, but the destination folder is still empty

![autosave options](https://user-images.githubusercontent.com/22700182/170347850-25392cc3-560e-4c80-907c-ec795d09cc2e.PNG)

![notepad++ version](https://user-images.githubusercontent.com/22700182/170347864-69ac2ef6-a53e-4b2c-b388-25f83529b19f.PNG)
.

**Comment by francostellari** [comment]
Hello, in my testing the feature seems to be working. 
Perhaps the folder is not valid?
Please note that the plugin is undergoing a major rewrite and this feature will not be supported in the new version.
N++ has been taking care of saving unamed files on closure.
