### ISSUE TITLE
Update MenuIcons file and folder names to match Npp

### ISSUE THREAD

**Issue by kiwichick888** [francostellari/NppPlugins#31]
Can you please update the file and folder names? Some of them no longer match Npp names which means the menu icons aren't displayed. 
For example:
1) "Sort Lines in Ascending Order.ico" should be "Sort Lines Lexicographically Ascending.ico"
2) "Close more" should be "Close Multiple Documents"

Also, there are a couple of spelling errors on the main MenuIcons page (https://github.com/francostellari/NppPlugins/tree/main/MenuIcons):
stabdard
diappear (this is spelled wrong twice)

**Comment by francostellari** [comment]
It would be very helpful if you could do the filename corrections and send
me an updated zip file

**Comment by kiwichick888** [comment]
> It would be very helpful if you could do the filename corrections and send me an updated zip file

Yes I can absolutely do that for you. Can you please just confirm for me what the folders ! and @ refer to - are they document context menu and tab context menu? Also, how would you like me to send you the zip file? Post it (or a link to it) here or do you have an email address you'd like me to use?

**Comment by francostellari** [comment]
I have made some corrections. You can work off this latest version: https://github.com/francostellari/NppPlugins/blob/main/MenuIcons/EN-US.zip
You can attach the new zip file here to make a pull request against that file.
![image](https://user-images.githubusercontent.com/50019234/196568770-3cc0dade-3291-4ade-a1f2-4f297cbd80f8.png)

**Comment by kiwichick888** [comment]
> I have made some corrections. You can work off this latest version: https://github.com/francostellari/NppPlugins/blob/main/MenuIcons/EN-US.zip You can attach the new zip file here to make a pull request against that file. ![image](https://user-images.githubusercontent.com/50019234/196568770-3cc0dade-3291-4ade-a1f2-4f297cbd80f8.png)

Thanks! Here is my updated set. I've included a note regarding some of the changes I made and why I made them. 
[EN-US updated.zip](https://github.com/francostellari/NppPlugins/files/9815852/EN-US.updated.zip)

**Comment by kiwichick888** [comment]
Hi Franco, sorry to open this again but I notice that, although the updated zip you gave me the link to had some corrections, subsequent versions of MenuIcons have gone back to the old errors. 

For example:
1. The "Sort Lines in Ascending Order" icon should be "Sort Lines Lexicographically Ascending".
2. The "Close more" folder should be "Close Multiple Documents".
3. The "Help contents" icon should be "Notepad++ Online User Manual".

**Comment by francostellari** [comment]
@kiwichick888 I think it due to the ever changing M++ menus.
Can you send me an updated zip file with the corrections in the filenames?
I would like to include it with the next releases that is fixing issue #48

**Comment by Yaron10** [comment]
@francostellari,

Thank you for your ongoing work.
The recent versions are perfect! 👍 

[Updated MenuIcons Hebrew](https://github.com/francostellari/NppPlugins/files/12173866/MenuIcons.zip).
(Includes icons for "Change History" and more).

**Comment by kiwichick888** [comment]
> @kiwichick888 I think it due to the ever changing M++ menus. Can you send me an updated zip file with the corrections in the filenames? I would like to include it with the next releases that is fixing issue #48

@francostellari

Hi Franco, I have gone through every folder and made changes. Here is a zip file containing the updated icons and/or folders. I would strongly recommend checking my work in case I've made any errors as they are based purely on my Npp installation.

[MenuIcons_dll_2v03_x32-updated by kiwichick888.zip](https://github.com/francostellari/NppPlugins/files/12180762/MenuIcons_dll_2v03_x32-updated.by.kiwichick888.zip)
