### ISSUE TITLE
RunMe: icons can not be deactivated in toolbar

### ISSUE THREAD

**Issue by GwenDragon** [francostellari/NppPlugins#37]
The options of RunMe 1.60 plugin does allow to disable icons in toolbar.
But after deselecting all except one in section "Toolbar Icons (require restart)", hitting OK button and restarting Notepad++ the icons are not removed from toolbar.

Using:
Windows 11 22H2 64bit

Notepad++ v8.4.8   (64-bit)
Build time : Dec 24 2022 - 19:40:27
Path : P:\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 22H2
OS Build : 22621.963
Current ANSI codepage : 1252
Plugins : 
    ComparePlus (1.1)
    Explorer (1.9.5)
    HexEditor (0.9.12)
    LanguageHelp (1.7.5)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExec (0.8.2)
    NppExport (0.4)
    NppFTP (0.29.12)
    RegexTrainer (1)
    RunMe (1.6)
    XMLTools (3.1.1.13)

**Comment by francostellari** [comment]
Thank you for finding the bug. It also affects TopMost plugin.
It will be fixed in the next release.
