### ISSUE TITLE
[Take Notes] [Bug] Periods on the first line will break the file extension if `$firstline$` is used

### ISSUE THREAD

**Issue by ijre** [francostellari/NppPlugins#43]
My file extension is "_note.txt"

Without any periods on the first line:
![image](https://github.com/francostellari/NppPlugins/assets/33820042/e12f591f-a43c-4000-8a50-da3c98c4ae8e)

With periods (tested with just one period, problem persists):
![image](https://github.com/francostellari/NppPlugins/assets/33820042/6571194e-a9b9-45c3-b790-943b00d22344)

Effect carries over to the real file name as well.

**Comment by francostellari** [comment]
I believe this is due to the fact that it interpret the presence of the "." as a statement that you already added the extension that you wanted and thus it does not add the standard one.

**Comment by francostellari** [comment]
I will fix it in the next release... when I have time.

**Comment by francostellari** [comment]
@ijre please try the new version v1.2.5
https://github.com/francostellari/NppPlugins/blob/main/TakeNotes/TakeNotes_dll_1v25_x64.zip
