### ISSUE TITLE
Auto save conflicts with the search window/feature

### ISSUE THREAD

**Issue by ILoveSkilledCoders** [francostellari/NppPlugins#44]
Hi there,

So this has been happening for months now, and it's causing me a lot of issues. I've even lost text and links because of it.

I'm in the middle of searching pressing enter over & over to search my large note, and then auto save happens, bumps my curser from the enter key, and this somehow starts typing over text that's in the file within NPP to puts spaces over the text even though I'm not typing, I'm just pressing enter to find the right spot.

I hope that makes sense, it's hard to explain.

You can see how it's flickering so fast that it takes over my search.

My website coder says it is a bug, but he's not here right now to tell me exactly how to write this.

If you can fix, it would be much appreciated.

Thanks

**Comment by francostellari** [comment]
I'm sorry for you issues. Can you let me know more specifics about the version of npp and autosave? At the moment i cannot imagine what is accusing your problem

**Comment by ILoveSkilledCoders** [comment]
> I'm sorry for you issues. Can you let me know more specifics about the version of npp and autosave? At the moment i cannot imagine what is accusing your problem

Ok, the version of NPP is 8.4.8

version of autosave is 1.61

It would really help if I could copy the version from the popup. :)

Thanks

**Comment by francostellari** [comment]
The flickering of the tabs is a feature of the older AutoSave plugin.
Please upgrade to v2.00 to solve your problem.
Note that some features are not implemented/available anymore, so make sure it satisfies your needs.

**Comment by ILoveSkilledCoders** [comment]
> The flickering of the tabs is a feature of the older AutoSave plugin.
> Please upgrade to v2.00 to solve your problem.
> Note that some features are not implemented/available anymore, so make sure it satisfies your needs.

What features are missing? I just need it to save every 1 min. or something.

And I just installed it about a month & a half ago, when did it come out? Doesn't NPP tell me when there's an update for plugins?

Also, why would it be a feature & not a bug? What's the feature supposed to do?

Thanks
