### ISSUE TITLE
[Menu Icons] Strip/replace double quotes (") from filenames

### ISSUE THREAD

**Issue by jmaraujouy** [francostellari/NppPlugins#46]
Hello, Franco.

I have noticed that there are some menu entries that contains double quotes (") in their name.

The thing is, _Menu Icons_ is not stripping the double quotes (") from the expected icon filename, which makes impossible to assign them an icon, since _double quotes_ are reserved characters and cannot be used in filenames.

Just to give you an example, the plugin _Code Alignment_ has a menu item with the name «**_Align by quote (")_**». If I generate a list from _Menu Icons_ config, the suggested filename is: `Align by quote (").ico`, which is impossible to name the file.

![imagen](https://github.com/francostellari/NppPlugins/assets/117078256/471a4e0b-9585-465b-a70b-f13a108f480b)

I know some characters are being stripped or replaced with a _number/pound sign_ (#), but this is not the case with the double quotes. I haven't tested with any other reserved characters: `< > : / \ | ? *`.

Can this be fixed in a future release?

Thanks!

PS: And thank you so much for the plugin, which makes _Notepad++_ a lot more enjoyable to use. 😉

**Comment by jmaraujouy** [comment]
> I know some characters are being stripped or replaced with a _number/pound sign_ (#), but this is not the case with the double quotes. I haven't tested with any other reserved characters: `< > : / \ | ? *`.

I can confirm it also happens with the 'greater-than' character.

![imagen](https://github.com/francostellari/NppPlugins/assets/117078256/8114e33f-3e90-40d5-88de-d40ebf2bfeff)

Generated list:
`ASCII -> HEX	22036	==>	d:\MenuIcons\Complementos\Converter\ASCII -> HEX.ico`
`HEX -> ASCII	22037	==>	d:\MenuIcons\Complementos\Converter\HEX -> ASCII.ico`

**Comment by francostellari** [comment]
I will add the character stripping in the next release... when I have time.

**Comment by jmaraujouy** [comment]
@francostellari Great! Thank you.

**Comment by francostellari** [comment]
@jmaraujouy please manually test the new v2.0.3. It should solve your problems
https://github.com/francostellari/NppPlugins/blob/main/MenuIcons/MenuIcons_dll_2v03_x64.zip

**Comment by jmaraujouy** [comment]
@francostellari Hi, Franco. Thanks for the quick fix. I can confirm this issue is solved. 👍🏻👍🏻

![imagen](https://github.com/francostellari/NppPlugins/assets/117078256/41486bb1-17b6-452c-a848-e216a944aa88)

Thank you!

PS: As you can see in the screenshot, I made a new icon set using Microsoft's Fluent UI icons.

I made icons for every menu/submenu/context menu. I just need to make a new set for npp _light theme_.
As soon as it is done I can post them here. Let me know if you're interested.
