### ISSUE TITLE
Encoding in MenuIcons.txt

### ISSUE THREAD

**Issue by vodek3** [francostellari/NppPlugins#48]
Hello!

If the Notepad++ interface language is used, which contains, in addition to standard Latin characters, others (in addition to Standard ASCII - a-z, A-Z and #$%^&*()-_+!), then in the MenuIcons.txt, characters other than those mentioned are replaced by the symbol "?"
It's problem... Completely impossible to use MenuIcons.txt to create an icon library.

**Example couple lines from MenuIcons.txt for Russian Translation:**
```
&????	-1	==>	C:\Program Files\Notepad++\Plugins\MenuIcons\EN-US\????.ico
?????	41001	==>	C:\Program Files\Notepad++\Plugins\MenuIcons\EN-US\????\?????.ico
???????...	41002	==>	C:\Program Files\Notepad++\Plugins\MenuIcons\EN-US\????\???????.ico

```
Correct is: 
```
&Файл	-1	==>	C:\Program Files\Notepad++\Plugins\MenuIcons\EN-US\Файл.ico
Новый	41001	==>	C:\Program Files\Notepad++\Plugins\MenuIcons\EN-US\Файл\Новый.ico
Открыть...	41002	==>	C:\Program Files\Notepad++\Plugins\MenuIcons\EN-US\Файл\Открыть.ico
```

**Example couple lines from MenuIcons.txt for Czech Translation:**
```
&Otev?нt...	41002	==>	C:\Program Files\Notepad++\Plugins\MenuIcons\EN-US\Soubor\Otev?нt.ico
Otev?нt slo?ku obsahujнcн akt. &soubor v	-1	==>	C:\Program Files\Notepad++\Plugins\MenuIcons\EN-US\Soubor\Otev?нt slo?ku obsahujнcн akt. soubor v.ico
Pr?zkumnнk	41019	==>	C:\Program Files\Notepad++\Plugins\MenuIcons\EN-US\Soubor\Otev?нt slo?ku obsahujнcн akt. soubor v\Pr?zkumnнk.ico
```

Correct is: 
```
&Otevřít...	41002	==>	C:\Program Files\Notepad++\Plugins\MenuIcons\EN-US\Soubor\Otevřít.ico
Otevřít složku obsahující akt. &soubor v	-1	==>	C:\Program Files\Notepad++\Plugins\MenuIcons\EN-US\Soubor\Otevřít složku obsahující akt. soubor v.ico
Průzkumník	41019	==>	C:\Program Files\Notepad++\Plugins\MenuIcons\EN-US\Soubor\Otevřнt složku obsahující akt. soubor v\Průzkumník.ico

```
With most other Notepad++ translations, situation exactly the same

**Comment by Yaron10** [comment]
👍

**Comment by francostellari** [comment]
This problem should be fixed in 2v04: 
https://github.com/francostellari/NppPlugins/blob/main/MenuIcons/MenuIcons_dll_2v04_x64.zip

**Comment by Yaron10** [comment]
@francostellari,

Great. 👍 
Thank you.

**Comment by vodek3** [comment]
It's work. Thank You, Franco! 👍
![image](https://github.com/francostellari/NppPlugins/assets/25941601/1520d9a5-9bc5-4e5e-9082-b09192b62a23)
