### ISSUE TITLE
[Menu Icons] Regression: Strip ... in German locale does't work any more

### ISSUE THREAD

**Issue by bege10** [francostellari/NppPlugins#54]
Hello,
there is a regression in 2v03 and 2v04. With option `plain text match` all entries with `...` with German locale have no icons any more. This had been fixed in[ #10](https://github.com/francostellari/NppPlugins/issues/10#issuecomment-924527507).

**Comment by bege10** [comment]
@francostellari Can you, please, fix this regression?
Thanks!

**Comment by francostellari** [comment]
@bege10 I cannot see or reproduce your problem.
I switched to German.
I'm targeting File/Open... in German:
```
&Öffnen ?	41002	==>	C:\scoop\apps\notepadplusplus\current\Plugins\MenuIcons\EN-US\Datei\Öffnen.ico
```
I created an icon with the pecified path
![image](https://github.com/francostellari/NppPlugins/assets/50019234/e6929450-27d3-464b-9372-39de490ef9e7)
The Icon shows in the menu:
![image](https://github.com/francostellari/NppPlugins/assets/50019234/fee1d2dc-9a2f-4bee-8e89-44e682e35f22)

**Comment by bege10** [comment]
With these settings
![Screenshot_341](https://github.com/francostellari/NppPlugins/assets/1184237/01d4990c-e146-4c51-af92-e6b7276d2f37)
with 2v02 I have this
![Screenshot_339](https://github.com/francostellari/NppPlugins/assets/1184237/10038485-6ce0-47fd-912f-46bc9c9b41ee)
and with 2v03 and v04 I have this
![Screenshot_340](https://github.com/francostellari/NppPlugins/assets/1184237/f00030d4-55a2-451b-a958-c660ddf17a75)

**Comment by francostellari** [comment]
Perhaps the expected file path is different.
You need to use Generate List and make sure that whatever version you use the filenames match the expected values.

**Comment by bege10** [comment]
> Perhaps the expected file path is different. You need to use Generate List and make sure that whatever version you use the filenames match the expected values.

This is the same NPP version, I only change the MenuIcons.dll in the C:\Program Files\Notepad++\plugins\MenuIcons folder and restart NPP.

2v02: &Öffnen ?	41002	==>	C:\Program Files\Notepad++\Plugins\MenuIcons\DE\Datei\Öffnen.ico
2v03: &Öffnen ?	41002	==>	C:\Program Files\Notepad++\Plugins\MenuIcons\DE\Datei\Öffnen ?.ico

The ` ?` we know already from #10

**Comment by francostellari** [comment]
@bege10 I believe [v2.05](https://github.com/francostellari/NppPlugins/blob/main/MenuIcons/MenuIcons_dll_2v05_x64.zip) should fix this issue

**Comment by bege10** [comment]
> @bege10 I believe [v2.05](https://github.com/francostellari/NppPlugins/blob/main/MenuIcons/MenuIcons_dll_2v05_x64.zip) should fix this issue

Yep, thank you very much!
