### ISSUE TITLE
small graphical bug

### ISSUE THREAD

**Issue by HelloWorldFR** [francostellari/NppPlugins#56]
Hello,

When we are modifying a new tab, the symbol "*" appear on the left side of the name.

![01.png](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/119363820/68aa1944-65bf-479e-93d6-52f7cf956bb2)

But when we move the tab, the symbol dont follow the tab.
![02.png](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/119363820/e03bf499-89e8-4d5e-a24d-9b0e086a1ecd)

And we lose the original red icon when the file is updated and not saved (blue when saved):
![red_Icon](https://github.com/francostellari/NppPlugins/assets/119363820/fdfca16e-b0b2-450c-a31b-33644e88424d)
we can see them if "Show shell icon on the tabs" is unchecked but we lose the symbol.

Best regard

#Debug info
Notepad++ v8.5.7   (64-bit)
Build time : Sep  6 2023 - 23:13:49
Path : D:\npp.8.5.7.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.3448
Current ANSI codepage : 1252
Plugins : 
    MenuIcons (2.0.3)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NppSnippets (1.7.1)
    SurroundSelection (1.4.1)

**Comment by francostellari** [comment]
@HelloWorldFR I believe [v2.05](https://github.com/francostellari/NppPlugins/blob/main/MenuIcons/MenuIcons_dll_2v05_x64.zip) should fix this issue
