### ISSUE TITLE
[Take Notes]  Request to reintroduce previous special substitution strings

### ISSUE THREAD

**Issue by kiyn** [francostellari/NppPlugins#63]
I realized that in recent updates you removed the ability to use some special substitution strings that I had been using for some time and that were valuable to me.
Would it be possible to restore them?

I was using them in Take Notes v1.24 (build 2021-11-10), they were:
`$year$ $month$ $day$ $hour$ $minute$`

Thank you very much

**Comment by francostellari** [comment]
Sorry, I lost the code at one point.
I reimplemented in v1.27.
Please try it out and let me know if it works.

**Comment by kiyn** [comment]
I tried the 64bit version on Notepad++ 8.6.4 and it works perfectly.
The help page is also correct.
Thank you very much for your work and for choosing to share it.
