### ISSUE TITLE
[Feature Request] TakeNote - Request for extra $date$ type filters

### ISSUE THREAD

**Issue by trevrr** [francostellari/NppPlugins#64]
I think it would be great to have some extra filters to work with.
Along with $date$ could we have $year$ and $month$ or event $weekno$ please?
$year$ returning current year
$month$ returning current month number 1...12
$weekno returning current week number 1..52 (or even 53)
Being able to add these to the folder structure would enable me, as someone with multiple hundred meeting notes, to file a lot better?

**Comment by francostellari** [comment]
The additional variables that you request were already available but there was a regression recently.
It's fixed in v1.27 which you currently need to install manually until it's made available by the plugin manager.

**Comment by trevrr** [comment]
Fantastic. That's super. I'll test and revert if there's any issues.
Thanks!!!
