### ISSUE TITLE
I'm not sure if it's because of the plugin. (AutoSave)

### ISSUE THREAD

**Issue by Melo159** [francostellari/NppPlugins#7]
I was using the Internet, and suddenly, a Notepad++ window pops up.

In my opinion, in order to autosave, it seems to switch to a Notepad++ window.

I'm not sure because it's an intermittent symptom, 
but if I delete the AutoSave plugin, the symptom seems to go away.

This is an intermittent symptom. So, maybe It could just be a problem with my computer.

**Comment by francostellari** [comment]
I cannot reproduce your problem. Can you provide more details such as the OS version, NPP version and the autosave.ini?

**Comment by Melo159** [comment]
It's an intermittent symptom, so I can't reproduce it right now.
I'll try it for a few days and see if it's okay.

But, I think...
I do not know when,
I think it's fine now.

WIN10 21H1 / NPP 8.1.3 

[Options]
Timer=1
SaveOnActivateApp=0
SaveOnTimer=1
SaveCurrentFileOnly=0
NamedFilesMode=1
UnNamedFilesMode=0
UnNamedFilesSaveFolder=$CDIR$utorecover
UnNamedFilesRecoverFolder=$CDIR$utorecover
MaxFileSize=10000

**Comment by Melo159** [comment]
I've been testing it for a few days,
I think it's fine now.
