### ISSUE TITLE
[MenuIcons v1.2.3 x64] update corrupts folder path

### ISSUE THREAD

**Issue by bege10** [francostellari/NppPlugins#9]
Thank you very much for this helpful plugin.

After updating to this version the icons are in the folder path `C:\Program Files\Notepad++\plugins\MenuIcons\MenuIcons` which is not compatible with the list created by the plugin and with the standard settings.

Because I have created icons for the German locale it is not good that the plugin overwrites the folder with the icons for the English locale. I recommend to put these icons in a subfolder, e.g. `C:\Program Files\Notepad++\plugins\MenuIcons\EN`. That would not overwrite folders for other locales, in my case ...\DE

**Comment by francostellari** [comment]
Please test the new version 1.24 of MenuIcons. The icon folder has been localized to EN-US.

**Comment by bege10** [comment]
Thank you.
